#' Roll 'lumped' genera to lowest common taxonomic resolution
#'
#' @description
#' This function replaces all 'lump' genera (generated by
#' \code{getInvertData(taxonFix = "lump")}) with the lowest common taxonomic
#' resolution for all genera in the lumped genus.
#'
#' @param inputdataset Input dataset that should generated from
#'  \code{getInvertData()}.
#'
#' @return A taxa by sample data frame with site, stream reach, and sample information.
#'
#' @details
#'  In some instances, like when calculating MMIs for example, it may be useful
#'  to roll the "lumped" genera to their lowest common taxonomic resolution
#'  (Subfamily, Family, or Order). This function gathers the lowest common taxonomic resolution all lump genus
#'  members share. The function then replaces the "lump genus" name
#'  (e.g., Elimia/Pleurocera) with the lowest common taxonomic resolution
#'  designation (e.g., Pleuroceridae). The function then sums occurrence or density data
#'  within duplicate broader taxonomic designations. For instance, if
#'  \code{taxonLevel = "Mixed"}, then observations among duplicated taxonomic unit
#'  columns would be summed (occurrences summed then converted to 0/1).
#'
#'  The input dataset should be directly generated by \code{getInvertData()}, with
#'  \code{taxonFix = "lump"}.
#'
#' @export

lumpRollUp <- function(inputdataset){

  ##gather the lumped genera names and relate it to the column names
  cols_to_update <- which(colnames(inputdataset) %in% gsub("\\/","\\.",.clust_labels$lump))

  ##get the lowest common taxonomic resolution within the lump genus
  update_cols <- .clust_labels$LowestTax[match(colnames(inputdataset)[cols_to_update], gsub("\\/","\\.",.clust_labels$lump))]

  ##replace column names with the updated names
  colnames(inputdataset)[cols_to_update] = update_cols

  ##sum duplicate columns in the dataframe, if they exist
  outputdataset <- inputdataset %>%
    tidyr::pivot_longer(cols = !(Agency:Gen_ID_Prop)) %>%
    mutate(name = str_remove(name, "\\.\\d+$")) %>%
    dplyr::group_by_at(vars(Agency:Gen_ID_Prop,name)) %>%
    dplyr::summarise(value = sum(value)) %>%
    tidyr::pivot_wider(names_from = name, values_from = value) %>%
    ungroup()

  ##correct for instances in which everything is occurrence
  if(all(colSums(inputdataset[cols_to_update] > 1) == 0)) {
    outputdataset <- outputdataset %>%
      mutate(across(.cols = -(Agency:Gen_ID_Prop), ~1 * (. > 0)))
  }

  ##return the output dataset
  return(outputdataset)
}
